name: Pruebas

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Configurar JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Configurar gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Otorgar permisos de ejecución a gradle
        run: chmod +x gradlew
      - name: Ejecutar test con gradle
        run: ./gradlew test
